function [axeshandels , figure1] = createROIfigure
%CREATEFIGURE1

%  Auto-generated by MATLAB on 27-Sep-2016 11:42:29

% Create figure
num_traces = 9;

figure1 = figure('units','normalized','outerposition',[0 0 1 1]);
axeshandels = cell(1,num_traces);
for i = 1:numel(axeshandels)
    axeshandels{i} = containers.Map;
end
% Create axes

axeshandels{1}('trace') = axes('Parent',figure1,...
    'Position',[0.0303125 0.851838456901748 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{1}('spikes') = axes('Parent',figure1,...
    'Position',[0.0290625 0.711965039180229 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{2}('trace') = axes('Parent',figure1,...
    'Position',[0.0275 0.51918153402559 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{2}('spikes') = axes('Parent',figure1,...
    'Position',[0.0269791666666667 0.377944420623528 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{3}('trace') = axes('Parent',figure1,...
    'Position',[0.0269791666666667 0.198562977324559 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{3}('spikes') = axes('Parent',figure1,...
    'Position',[0.0259375 0.0562949360874455 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{4}('trace') = axes('Parent',figure1,...
    'Position',[0.353541666666667 0.85217122474724 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{4}('spikes') = axes('Parent',figure1,...
    'Position',[0.353020833333333 0.711965039180229 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{5}('trace') = axes('Parent',figure1,...
    'Position',[0.3525 0.517119678355487 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{5}('spikes') = axes('Parent',figure1,...
    'Position',[0.351458333333333 0.376913492788477 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{6}('trace') = axes('Parent',figure1,...
    'Position',[0.350416666666667 0.196501121654456 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{6}('spikes') = axes('Parent',figure1,...
    'Position',[0.349895833333333 0.0532021525822909 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{7}('trace') = axes('Parent',figure1,...
    'Position',[0.674375 0.850109369077137 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{7}('spikes') = axes('Parent',figure1,...
    'Position',[0.674375 0.709903183510128 0.295535714285715 0.135714285714287]);

% Create axes
axeshandels{8}('trace') = axes('Parent',figure1,...
    'Position',[0.674375 0.518150606190538 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{8}('spikes') = axes('Parent',figure1,...
    'Position',[0.673854166666667 0.376913492788477 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{9}('trace') = axes('Parent',figure1,...
    'Position',[0.674375 0.197532049489508 0.295535714285714 0.135714285714287]);

% Create axes
axeshandels{9}('spikes') = axes('Parent',figure1,...
    'Position',[0.673854166666667 0.0542330804173424 0.295535714285714 0.135714285714287]);

